// client/src/app/components/header/header.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { State, SslError } from '../../../../../server/src/types';
import { AuthRepository } from '../../state/auth.repository';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent implements OnInit {
  @Input('showDetailed') showDetailed: boolean = true;
  @Input('state') state!: State | null;
  @Input('errors') errors: SslError[] = [];
  @Input('minimized') minimized: boolean = false;
  @Input('showGrid') showGrid: boolean = true;

  @Output('changeMinimized') minimized$ = new EventEmitter<boolean>();
  @Output('changeShowGrid') showGrid$ = new EventEmitter<boolean>();

  constructor(private readonly authRepository: AuthRepository) {}

  signout() {
    this.authRepository.logout();
  }
  ngOnInit(): void {}
}

<nav class="navbar bg-base-300">
  <div class="flex-1">
    <a
      class="text-sm font-bold leading-relaxed inline-flex mx-4 py-2 whitespace-nowrap uppercase items-center"
      href="/"
    >
      <img class="w-8 h-8" src="assets/ssl-check-dashboard-min.png" />
      <span class="ml-2">SSL Dashboard</span>
    </a>
  </div>
  <div class="flex-none">
    <ul
      class="menu-horizontal p-0 flex items-center space-x-2"
      *ngIf="showDetailed"
    >
      <li>
        <button
          class="btn bg-base-100 text-base-content rounded-lg"
          type="button"
          title="Logout"
          (click)="signout()"
        >
          <app-logout-icon></app-logout-icon>
        </button>
      </li>
      <li>
        <button
          class="btn bg-base-100 text-base-content rounded-lg"
          type="button"
          title="Change Style"
          (click)="minimized$.emit(!minimized)"
        >
          <app-maximize-icon *ngIf="minimized"></app-maximize-icon>
          <app-minimize-icon *ngIf="!minimized"></app-minimize-icon>
        </button>
      </li>
      <li>
        <button
          class="btn bg-base-100 text-base-content rounded-lg"
          type="button"
          title="Change Style"
          (click)="showGrid$.emit(!showGrid)"
        >
          <app-table-icon *ngIf="showGrid"></app-table-icon>
          <app-grid-icon *ngIf="!showGrid"></app-grid-icon>
        </button>
      </li>
      <li>
        <app-info [errors]="errors" [state]="state"></app-info>
      </li>
    </ul>
  </div>
</nav>

// client/src/components/Header.svelte
<script lang="ts">
    import Status from './Status.svelte';
    import LogoutIcon from '../icons/logout-icon.svelte';
    import MinimizeIcon from '../icons/minimize-icon.svelte';
    import MaximizeIcon from '../icons/maximize-icon.svelte';
    import { user, appstate } from '../shared/store.js';
</script>

<nav
    class="
    relative
    flex flex-wrap
    items-center
    justify-between
    px-2
    py-3
    bg-gray-600
    shadow-xl
    mb-3
"
>
    <div
        class="
        container
        px-4
        mx-auto
        flex flex-wrap
        items-center
        justify-between
    "
    >
        <div
            class="
            w-full
            relative
            flex
            justify-between
            lg:w-auto
            px-4
            lg:static lg:block lg:justify-start
        "
        >
            <a
                class="
                text-sm
                font-bold
                leading-relaxed
                inline-block
                mr-4
                py-2
                whitespace-nowrap
                uppercase
                text-white
            "
                href="/"
            >
                SSL Dashboard
            </a>
        </div>
        <div
            class="lg:flex flex-grow items-center sm:width-full"
            id="example-navbar-warning"
        >
            <ul class="flex flex-row list-none ml-auto">
                <li class="nav-item">
                    <button
                        type="button"
                        title="Logout"
                        on:click={user.signout}
                        class="bg-gray-700 text-white cursor-pointer relative rounded-full p-2 mr-3 focus:outline-none"
                    >
                        <LogoutIcon />
                    </button>
                </li>
                <li class="nav-item">
                    <button
                        type="button"
                        title="Change Style"
                        on:click={appstate.toggleMinified}
                        class="bg-gray-700 text-white cursor-pointer relative rounded-full p-2 mr-3 focus:outline-none"
                    >
                        {#if $appstate.minified}
                            <MaximizeIcon />
                        {:else}
                            <MinimizeIcon />
                        {/if}
                    </button>
                </li>
                <li class="nav-item">
                    <Status />
                </li>
            </ul>
        </div>
    </div>
</nav>
